# Form implementation generated from reading ui file 'help_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Help(object):
    def setupUi(self, Help):
        Help.setObjectName("Help")
        Help.resize(514, 254)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons:MChat.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Help.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(Help)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=Help)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Help)
        QtCore.QMetaObject.connectSlotsByName(Help)

    def retranslateUi(self, Help):
        _translate = QtCore.QCoreApplication.translate
        Help.setWindowTitle(_translate("Help", "MChat Help"))
        self.label_2.setText(_translate("Help", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">MChat Help</span></p><p>Parameter options (when start from CLI)</p><p>    -s server_name : start immediatly as server (ex. MChat -s &quot;SERVER ONE&quot; )</p><p>    -c client_name : start immediatly as client (ex. MChat -c &quot;PC-MVALAGUZ&quot;)</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Help = QtWidgets.QDialog()
    ui = Ui_Help()
    ui.setupUi(Help)
    Help.show()
    sys.exit(app.exec())
