# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mchat_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(261, 318)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/MValaguz/.designer/backup/icon/MChat.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.o_messaggi = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o_messaggi.sizePolicy().hasHeightForWidth())
        self.o_messaggi.setSizePolicy(sizePolicy)
        self.o_messaggi.setObjectName("o_messaggi")
        self.verticalLayout.addWidget(self.o_messaggi)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.e_invia_messaggio = QtWidgets.QLineEdit(self.centralwidget)
        self.e_invia_messaggio.setObjectName("e_invia_messaggio")
        self.verticalLayout.addWidget(self.e_invia_messaggio)
        self.nomi_pc = QtWidgets.QComboBox(self.centralwidget)
        self.nomi_pc.setObjectName("nomi_pc")
        self.verticalLayout.addWidget(self.nomi_pc)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionConnect = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/connect.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect.setIcon(icon1)
        self.actionConnect.setObjectName("actionConnect")
        self.actionCreate_Server = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/create_server.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_Server.setIcon(icon2)
        self.actionCreate_Server.setObjectName("actionCreate_Server")
        self.actionClear_my_chat = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/clear.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear_my_chat.setIcon(icon3)
        self.actionClear_my_chat.setObjectName("actionClear_my_chat")
        self.actionReduce_to_systray = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/systray.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReduce_to_systray.setIcon(icon4)
        self.actionReduce_to_systray.setObjectName("actionReduce_to_systray")
        self.actionProgram_Info = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/info.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProgram_Info.setIcon(icon5)
        self.actionProgram_Info.setObjectName("actionProgram_Info")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/help.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon6)
        self.actionHelp.setObjectName("actionHelp")
        self.toolBar.addAction(self.actionCreate_Server)
        self.toolBar.addAction(self.actionConnect)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClear_my_chat)
        self.toolBar.addAction(self.actionReduce_to_systray)
        self.toolBar.addAction(self.actionProgram_Info)
        self.toolBar.addAction(self.actionHelp)
        self.label.setBuddy(self.o_messaggi)
        self.label_2.setBuddy(self.e_invia_messaggio)

        self.retranslateUi(MainWindow)
        self.toolBar.actionTriggered['QAction*'].connect(MainWindow.slot_Connessione)
        self.e_invia_messaggio.returnPressed.connect(MainWindow.slot_Connessione)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MChat 1.1"))
        self.label.setText(_translate("MainWindow", "Messages:"))
        self.label_2.setText(_translate("MainWindow", "Send:"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionConnect.setToolTip(_translate("MainWindow", "Connect to a server PC as a client"))
        self.actionCreate_Server.setText(_translate("MainWindow", "Create Server"))
        self.actionCreate_Server.setToolTip(_translate("MainWindow", "Create a server connection on my own computer"))
        self.actionClear_my_chat.setText(_translate("MainWindow", "Clear my chat"))
        self.actionClear_my_chat.setToolTip(_translate("MainWindow", "Clear my chat (F1 shortcut key)"))
        self.actionClear_my_chat.setShortcut(_translate("MainWindow", "F2"))
        self.actionReduce_to_systray.setText(_translate("MainWindow", "Reduce to systray"))
        self.actionReduce_to_systray.setToolTip(_translate("MainWindow", "Reduce to systray"))
        self.actionReduce_to_systray.setShortcut(_translate("MainWindow", "F3"))
        self.actionProgram_Info.setText(_translate("MainWindow", "Program Info"))
        self.actionProgram_Info.setToolTip(_translate("MainWindow", "Program Info"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setToolTip(_translate("MainWindow", "Help"))
        self.actionHelp.setShortcut(_translate("MainWindow", "F1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

